version: '3.2'

volumes:
  aiart-pg-data:
    external: true
  aiart-pgadmin-data:
    external: true

services:
  postgres:
    container_name: ai-art-db
    image: postgres
    restart: always
    volumes:
      - aiart-pg-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: puma
    ports:
     - "5432:5432"
